config/routes.rb
CrimeMap::Application.routes.draw do

  resources :comments, :only => [:create, :destroy]
  devise_for :users

  get "comments/create"
  get "crimes/stats"
  get "crimes/index"

   root 'crimes#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :length => {:minimum => 1}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.js {
          render :create
        }
        format.html {
          redirect_to crimes_index_path
        }
      end
    else
      render :js => 'alert("Comment must be at least 1 character")', :status => :forbidden
    end
  end
  def destroy
      @comment = Comment.find(params[:id])
    if @comment.present?
      @comment.destroy
    end
    redirect_to root_url
end 

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  
def stats
    url = "http://data.police.uk/api/crimes-street/all-crime?lat=#{params[:lat]}&lng=#{params[:lng]}"
    #render :json => File.read('spec/examples/street_crime.json')
    render :json => HTTParty.get(url)
  end

def index
     @comments = Comment.all
     @comment = Comment.new
  end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/views/comments/_comment.erb
<li class="comment"><%= comment.content %><span class="remove"><%= link_to 'Destroy', comment_path( comment), :method => :delete %></span></li>

app/views/comments/_comments_list.erb
<% @comments.each do |comment|%>
  <%= render :partial => 'comments/comment', :locals => {:comment => comment} %>
<% end %>

app/views/comments/create.js.erb
$('#comments').append('<%= escape_javascript(render(@comment)) %>');

app/views/crimes/index.html.erb
<center><h1>See Crimes in your Area</h1><center>
		<h2>Using data from police.uk<h2>

<h3><%= link_to "Sign up", new_user_registration_path, :class => "btn"%>
</br>
<%= link_to "Login", user_session_path, :class => "btn"%>
</br>
<%= link_to "Sign out", destroy_user_session_path,:method=>'delete', :class => "btn"%>
<div></div></h3>

<div id="map-canvas"></div>

<div id="crime-chart"></div>

<div id="comments">
  <%= render 'comments/comments_list' %>
</div>

<div id="new-comment-box">
  <%= form_for @comment, :remote => true, :authenticity_token => true, :id => "comment-form" do |f| %>
    <%= f.text_area :content, :cols => 65, :rows => 5, :placeholder => "Your comment...", :id => "new-comment" %></br>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAfvHzBJvdyMl6sX1XjXEz-j02_q95TQ8k&sensor=false">
  </script>

  <title>Police-Uk Map</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>